# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f87f1bfdb2a55fd8fa6043620a0f97dceed0ee7090e20f9d3bda4cfd8b89ad57d459ffaf453ed96d53f4f37353972d76f5406ebb0948207f593bdbb98a2e56

test:
  secret_key_base: 4a9e55b708285380f56cd314435173ff1d36f312a737d5935cdadc7cff54617d9783c1c8eee20ccdd24ecbaf624b2fc56ba22ec738b5c12873ec9d9b243d9227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
